# Generated by Django 5.2 on 2025-05-18 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('NEW_ORDER', 'New Order'), ('ORDER_STATUS', 'Order Status Change'), ('LOW_STOCK', 'Low Stock Alert'), ('SYSTEM', 'System Notification')], max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('processing_method', models.CharField(choices=[('NONE', 'None/Raw'), ('PEELED', 'Peeled'), ('CHOPPED', 'Chopped'), ('BLENDED', 'Blended'), ('BOILED', 'Boiled'), ('FRIED', 'Fried'), ('DEEP_FRIED', 'Deep Fried'), ('ROASTED', 'Roasted'), ('STEAMED', 'Steamed'), ('BAKED', 'Baked'), ('GRILLED', 'Grilled'), ('SMOKED', 'Smoked'), ('MARINATED', 'Marinated'), ('PICKLED', 'Pickled'), ('FERMENTED', 'Fermented'), ('DRIED', 'Dried'), ('GROUND', 'Ground'), ('MIXED', 'Mixed'), ('OTHER', 'Other (specify in description)')], default='NONE', help_text='Processing method requested by customer', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='category_images/')),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='DeliveryAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_line_1', models.CharField(max_length=255)),
                ('address_line_2', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('landmark', models.CharField(blank=True, max_length=255, null=True)),
                ('phoneNumber', models.CharField(blank=True, max_length=15, null=True)),
                ('is_default', models.BooleanField(default=False)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('delivery_date', models.DateField()),
                ('time_slot', models.CharField(choices=[('MORNING', 'Morning (8AM - 11AM)'), ('AFTERNOON', 'Afternoon (12PM - 3PM)'), ('EVENING', 'Evening (4PM - 7PM)')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('shared_link', models.URLField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeliverySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_type', models.CharField(choices=[('ONETIME', 'One-time Delivery'), ('WEEKLY', 'Weekly Scheduled Delivery'), ('SUBSCRIPTION', 'Subscription')], default='ONETIME', max_length=20)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('time_slot', models.CharField(choices=[('MORNING', 'Morning (8AM - 11AM)'), ('AFTERNOON', 'Afternoon (12PM - 3PM)'), ('EVENING', 'Evening (4PM - 7PM)')], max_length=20)),
                ('is_recurring', models.BooleanField(default=False)),
                ('recurrence_type', models.CharField(blank=True, choices=[('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly')], max_length=10, null=True)),
                ('delivery_days', models.CharField(blank=True, help_text='Comma-separated days for weekly deliveries (mon,tue,wed,etc.)', max_length=100, null=True)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('times_fulfilled', models.IntegerField(default=0)),
                ('times_skipped', models.IntegerField(default=0)),
                ('times_modified', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GroupOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_by_leader', models.BooleanField(default=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('leader_discount_applied', models.BooleanField(default=False)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=20, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('SHIPPED', 'Shipped'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=12)),
                ('shipping_address', models.TextField()),
                ('delivery_location', models.TextField(blank=True, null=True)),
                ('delivery_option', models.CharField(choices=[('STANDARD', 'Standard Delivery'), ('EXPRESS', 'Express Delivery'), ('SCHEDULED', 'Scheduled Delivery'), ('GROUP', 'Group Delivery'), ('SUBSCRIPTION', 'Subscription Delivery')], default='STANDARD', max_length=20)),
                ('delivery_method', models.CharField(blank=True, max_length=20, null=True)),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('distance_km', models.FloatField(blank=True, null=True)),
                ('scheduled_delivery_date', models.DateField(blank=True, help_text='Date for a one-time scheduled delivery', null=True)),
                ('scheduled_delivery_time', models.CharField(blank=True, choices=[('MORNING', 'Morning (8AM - 11AM)'), ('AFTERNOON', 'Afternoon (12PM - 3PM)'), ('EVENING', 'Evening (4PM - 7PM)')], help_text='Time slot for a one-time scheduled delivery', max_length=20, null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('leader_discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('estimated_delivery_time', models.DateTimeField(blank=True, null=True)),
                ('actual_delivery_time', models.DateTimeField(blank=True, null=True)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('processing_method', models.CharField(choices=[('NONE', 'None/Raw'), ('PEELED', 'Peeled'), ('CHOPPED', 'Chopped'), ('BLENDED', 'Blended'), ('BOILED', 'Boiled'), ('FRIED', 'Fried'), ('DEEP_FRIED', 'Deep Fried'), ('ROASTED', 'Roasted'), ('STEAMED', 'Steamed'), ('BAKED', 'Baked'), ('GRILLED', 'Grilled'), ('SMOKED', 'Smoked'), ('MARINATED', 'Marinated'), ('PICKLED', 'Pickled'), ('FERMENTED', 'Fermented'), ('DRIED', 'Dried'), ('GROUND', 'Ground'), ('MIXED', 'Mixed'), ('OTHER', 'Other (specify in description)')], default='NONE', help_text='Processing method requested by customer', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(choices=[('KG', 'Kilograms (kg)'), ('G', 'Grams (g)'), ('L', 'Liters (L)'), ('ML', 'Milliliters (ml)'), ('PIECE', 'Piece'), ('DOZEN', 'Dozen'), ('BUNDLE', 'Bundle'), ('CRATE', 'Crate'), ('BAG', 'Bag'), ('BOX', 'Box'), ('PACKET', 'Packet'), ('OTHER', 'Other (specify in description)')], default='KG', help_text='Unit of measurement for this product', max_length=10)),
                ('stock_quantity', models.PositiveIntegerField(default=0)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductAssociation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence', models.FloatField(help_text='Probability that recommendation is purchased when product is purchased')),
                ('lift', models.FloatField(help_text='How much more likely recommendation is purchased with product vs. on its own')),
                ('support', models.FloatField(help_text='Percentage of orders containing both products')),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product_images/')),
                ('is_primary', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ProductProcessingMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('NONE', 'None/Raw'), ('PEELED', 'Peeled'), ('CHOPPED', 'Chopped'), ('BLENDED', 'Blended'), ('BOILED', 'Boiled'), ('FRIED', 'Fried'), ('DEEP_FRIED', 'Deep Fried'), ('ROASTED', 'Roasted'), ('STEAMED', 'Steamed'), ('BAKED', 'Baked'), ('GRILLED', 'Grilled'), ('SMOKED', 'Smoked'), ('MARINATED', 'Marinated'), ('PICKLED', 'Pickled'), ('FERMENTED', 'Fermented'), ('DRIED', 'Dried'), ('GROUND', 'Ground'), ('MIXED', 'Mixed'), ('OTHER', 'Other (specify in description)')], help_text='Processing method offered for this product', max_length=20)),
                ('is_default', models.BooleanField(default=False, help_text='This is the default processing method shown to customers')),
            ],
            options={
                'verbose_name': 'Product Processing Method',
                'verbose_name_plural': 'Product Processing Methods',
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(help_text='Unique ID to group purchases in a single order', max_length=36)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RelatedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_type', models.CharField(default='complementary', help_text='Describes how these products are related', max_length=50)),
                ('relevance_score', models.PositiveSmallIntegerField(default=10, help_text='1-10 score indicating how relevant this relationship is')),
                ('notes', models.TextField(blank=True, help_text='Optional notes about why these products are related', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-relevance_score', 'product__name'],
            },
        ),
        migrations.CreateModel(
            name='ScheduledDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_date', models.DateField()),
                ('time_slot', models.CharField(choices=[('MORNING', 'Morning (8AM - 11AM)'), ('AFTERNOON', 'Afternoon (12PM - 3PM)'), ('EVENING', 'Evening (4PM - 7PM)')], max_length=20)),
                ('delivery_notes', models.TextField(blank=True, null=True)),
                ('recurrence_type', models.CharField(choices=[('NONE', 'One-time'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly')], default='NONE', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Scheduled Delivery',
                'verbose_name_plural': 'Scheduled Deliveries',
                'ordering': ['delivery_date', 'time_slot'],
            },
        ),
        migrations.CreateModel(
            name='ScheduledItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('processing_method', models.CharField(default='NONE', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Optional name for this subscription', max_length=100)),
                ('duration', models.CharField(choices=[('TWO_WEEKS', 'Two Weeks'), ('ONE_MONTH', 'One Month'), ('THREE_MONTHS', 'Three Months'), ('SIX_MONTHS', 'Six Months'), ('CUSTOM', 'Custom Duration')], max_length=20)),
                ('frequency', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('BIWEEKLY', 'Bi-weekly'), ('MONTHLY', 'Monthly')], max_length=20)),
                ('delivery_days', models.CharField(blank=True, help_text='Comma-separated days for weekly deliveries (mon,tue,wed,etc.)', max_length=100, null=True)),
                ('time_slot', models.CharField(choices=[('MORNING', 'Morning (8AM - 11AM)'), ('AFTERNOON', 'Afternoon (12PM - 3PM)'), ('EVENING', 'Evening (4PM - 7PM)')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('next_delivery_date', models.DateField()),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('cancellation_date', models.DateField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True, null=True)),
                ('total_deliveries', models.PositiveIntegerField(default=0)),
                ('total_spent', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_method', models.CharField(default='CASH', max_length=50)),
                ('auto_renew', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
