# Generated by Django 5.2 on 2025-05-18 08:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('marketplace', '0001_initial'),
        ('registration', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='businessnotification',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='registration.businessprofile'),
        ),
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='marketplace.cart'),
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='marketplace.category'),
        ),
        migrations.AddField(
            model_name='deliveryaddress',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_addresses', to='registration.customerprofile'),
        ),
        migrations.AddField(
            model_name='deliverygroup',
            name='leader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='led_groups', to='registration.customerprofile'),
        ),
        migrations.AddField(
            model_name='deliveryschedule',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_schedules', to='registration.customerprofile'),
        ),
        migrations.AddField(
            model_name='deliveryschedule',
            name='delivery_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_deliveries', to='marketplace.deliveryaddress'),
        ),
        migrations.AddField(
            model_name='grouporder',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_orders', to='marketplace.deliverygroup'),
        ),
        migrations.AddField(
            model_name='grouporder',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_orders', to='registration.customerprofile'),
        ),
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='registration.customerprofile'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='marketplace.deliveryaddress'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketplace.deliverygroup'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='marketplace.deliveryschedule'),
        ),
        migrations.AddField(
            model_name='grouporder',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='group_order', to='marketplace.order'),
        ),
        migrations.AddField(
            model_name='businessnotification',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business_notifications', to='marketplace.order'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='marketplace.order'),
        ),
        migrations.AddField(
            model_name='product',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='registration.businessprofile'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='marketplace.category'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.product'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.product'),
        ),
        migrations.AddField(
            model_name='productassociation',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='associations', to='marketplace.product'),
        ),
        migrations.AddField(
            model_name='productassociation',
            name='recommendation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommended_for', to='marketplace.product'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='marketplace.product'),
        ),
        migrations.AddField(
            model_name='productprocessingmethod',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processing_methods', to='marketplace.product'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.product'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='relatedproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_related_products', to='marketplace.product'),
        ),
        migrations.AddField(
            model_name='relatedproduct',
            name='related_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_related_to', to='marketplace.product'),
        ),
        migrations.AddField(
            model_name='order',
            name='scheduled_delivery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='marketplace.scheduleddelivery'),
        ),
        migrations.AddField(
            model_name='scheduleditem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.product'),
        ),
        migrations.AddField(
            model_name='scheduleditem',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduleditems', to='marketplace.deliveryschedule'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='registration.customerprofile'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='delivery_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='marketplace.deliveryaddress'),
        ),
        migrations.AddField(
            model_name='order',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='marketplace.subscription'),
        ),
        migrations.AddField(
            model_name='deliveryschedule',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_schedules', to='marketplace.subscription'),
        ),
        migrations.AddIndex(
            model_name='deliverygroup',
            index=models.Index(fields=['code'], name='marketplace_code_77d204_idx'),
        ),
        migrations.AddIndex(
            model_name='deliverygroup',
            index=models.Index(fields=['delivery_date'], name='marketplace_deliver_0b5bdf_idx'),
        ),
        migrations.AddIndex(
            model_name='deliverygroup',
            index=models.Index(fields=['is_active'], name='marketplace_is_acti_8eb4b2_idx'),
        ),
        migrations.AddIndex(
            model_name='grouporder',
            index=models.Index(fields=['added_by_leader'], name='marketplace_added_b_d4cec7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='grouporder',
            unique_together={('group', 'order')},
        ),
        migrations.AddIndex(
            model_name='businessnotification',
            index=models.Index(fields=['business', 'is_read'], name='marketplace_busines_a847b4_idx'),
        ),
        migrations.AddIndex(
            model_name='businessnotification',
            index=models.Index(fields=['created_at'], name='marketplace_created_cff921_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'product')},
        ),
        migrations.AddIndex(
            model_name='productassociation',
            index=models.Index(fields=['product'], name='marketplace_product_9e3a85_idx'),
        ),
        migrations.AddIndex(
            model_name='productassociation',
            index=models.Index(fields=['lift'], name='marketplace_lift_994f80_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productassociation',
            unique_together={('product', 'recommendation')},
        ),
        migrations.AlterUniqueTogether(
            name='productprocessingmethod',
            unique_together={('product', 'method')},
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['order_id'], name='marketplace_order_i_d878f6_idx'),
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['timestamp'], name='marketplace_timesta_748333_idx'),
        ),
        migrations.AddIndex(
            model_name='relatedproduct',
            index=models.Index(fields=['product', 'relevance_score'], name='marketplace_product_9daf22_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='relatedproduct',
            unique_together={('product', 'related_product')},
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['customer', 'is_active'], name='marketplace_custome_ea3ca9_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['next_delivery_date'], name='marketplace_next_de_63ec98_idx'),
        ),
        migrations.AddIndex(
            model_name='deliveryschedule',
            index=models.Index(fields=['schedule_type'], name='marketplace_schedul_0f4841_idx'),
        ),
        migrations.AddIndex(
            model_name='deliveryschedule',
            index=models.Index(fields=['delivery_date'], name='marketplace_deliver_cf13ef_idx'),
        ),
        migrations.AddIndex(
            model_name='deliveryschedule',
            index=models.Index(fields=['is_active'], name='marketplace_is_acti_e93353_idx'),
        ),
    ]
