# Generated by Django 5.2 on 2025-06-15 22:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('code', models.CharField(blank=True, help_text='Promo code for this offer. Leave blank for automatic offers.', max_length=20, null=True, unique=True)),
                ('offer_type', models.CharField(choices=[('PERCENTAGE', 'Percentage Discount'), ('FIXED', 'Fixed Amount Discount'), ('BOGO', 'Buy One Get One Free'), ('BUNDLE', 'Bundle Discount'), ('FREESHIP', 'Free Shipping'), ('LOYALTY', 'Loyalty Points Bonus'), ('FLASH', 'Flash Sale')], max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, default=0.0, help_text='Discount value (percentage or fixed amount)', max_digits=10)),
                ('target_type', models.CharField(choices=[('ALL', 'All Users'), ('NEW', 'New Users Only'), ('RETURNING', 'Returning Users'), ('PREMIUM', 'Premium Users'), ('INACTIVE', 'Inactive Users'), ('SPECIFIC', 'Specific Users')], default='ALL', max_length=20)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('max_uses', models.PositiveIntegerField(default=0, help_text='Maximum number of times this offer can be used (0 for unlimited)')),
                ('max_uses_per_user', models.PositiveIntegerField(default=1, help_text='Maximum number of times a user can use this offer')),
                ('min_order_value', models.DecimalField(decimal_places=2, default=0.0, help_text='Minimum order value for the offer to apply', max_digits=10)),
                ('highlight_color', models.CharField(default='#FFC107', help_text='Color for highlighting this offer in the UI', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='offer_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_uses', models.PositiveIntegerField(default=0, help_text='Number of times this offer has been used')),
                ('applies_to_categories', models.ManyToManyField(blank=True, related_name='offers', to='marketplace.category')),
                ('applies_to_products', models.ManyToManyField(blank=True, related_name='offers', to='marketplace.product')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_offers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_used', models.DateTimeField(blank=True, null=True)),
                ('used', models.BooleanField(default=False)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_offers', to='marketplace.offer')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applied_offers', to='marketplace.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_offers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_added'],
            },
        ),
        migrations.AddIndex(
            model_name='offer',
            index=models.Index(fields=['code'], name='marketplace_code_396ff9_idx'),
        ),
        migrations.AddIndex(
            model_name='offer',
            index=models.Index(fields=['start_date', 'end_date'], name='marketplace_start_d_222333_idx'),
        ),
        migrations.AddIndex(
            model_name='offer',
            index=models.Index(fields=['is_active'], name='marketplace_is_acti_999e48_idx'),
        ),
        migrations.AddIndex(
            model_name='offer',
            index=models.Index(fields=['offer_type'], name='marketplace_offer_t_4aa8df_idx'),
        ),
        migrations.AddIndex(
            model_name='useroffer',
            index=models.Index(fields=['user', 'used'], name='marketplace_user_id_28561a_idx'),
        ),
        migrations.AddIndex(
            model_name='useroffer',
            index=models.Index(fields=['offer'], name='marketplace_offer_i_6c1f23_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='useroffer',
            unique_together={('user', 'offer')},
        ),
    ]
