# Generated by Django 5.2 on 2025-05-21 03:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_research', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marketpriceresearch',
            old_name='notes',
            new_name='remarks',
        ),
        migrations.AddField(
            model_name='market',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='market',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='marketpriceresearch',
            name='collected_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='marketpriceresearch',
            name='commodity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='price_records', to='market_research.commodity'),
        ),
        migrations.AlterField(
            model_name='marketpriceresearch',
            name='market',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_research', to='market_research.market'),
        ),
    ]
