# Generated by Django 5.2 on 2025-05-21 03:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_research', '0003_rename_notes_marketpriceresearch_remarks_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('source_type', models.CharField(choices=[('market', 'Market'), ('processor', 'Processor'), ('kiosk', 'Kiosk'), ('farm', 'Farm'), ('store', 'Retail Store'), ('distributor', 'Distributor'), ('other', 'Other')], default='market', max_length=50)),
                ('location', models.CharField(max_length=200)),
                ('region', models.CharField(max_length=100)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('transportation_cost', models.DecimalField(blank=True, decimal_places=2, help_text='Cost to transport goods to/from this source', max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('market', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_link', to='market_research.market')),
            ],
        ),
        migrations.AddField(
            model_name='marketpriceresearch',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='price_research', to='market_research.source'),
        ),
    ]
