# Generated by Django 5.2 on 2025-05-21 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_research', '0004_source_marketpriceresearch_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commodity',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
