# Generated by Django 5.2 on 2025-05-21 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_research', '0005_alter_commodity_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketpriceresearch',
            name='market',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='price_research', to='market_research.market'),
        ),
    ]
