# Generated by Django 5.2 on 2025-05-21 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market_research', '0006_alter_marketpriceresearch_market'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marketpriceresearch',
            name='market',
        ),
    ]
