# Generated by Django 5.2 on 2025-05-21 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_user_first_name_user_last_name_alter_user_firstname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
    ]
